<?php

namespace Robust\RealEstate\Providers;

use Illuminate\Support\ServiceProvider;
use Robust\RealEstate\Helpers\CoreSettingHelper;

/**
 * Class RealEstateServiceProvider
 * @package Robust\RealEstate\Providers
 */
class RealEstateServiceProvider extends ServiceProvider
{
    protected $commands = [
        'Robust\RealEstate\Console\Commands\AdvanceSearch',
        'Robust\RealEstate\Console\Commands\ListingDetail',
    ];
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->app->bind(CoreSettingHelper::class, function ($app) {
            return new CoreSettingHelper($app->make('Robust\RealEstate\Repositories\Website\CoreSettingRepository'));
        });
        $this->loadViewsFrom(__DIR__ . '/../../resources/views', 'real-estate');
        $this->register_includes();
    }

    public function register_includes()
    {
        $this->mergeConfigFrom(__DIR__ . '/../../config/permissions.php', 'real-estate.permissions');
        $this->mergeConfigFrom(__DIR__ . '/../../config/advance-search.php', 'real-estate.search');
        $this->mergeConfigFrom(__DIR__ . '/../../config/listing-detail.php', 'real-estate.detail');
        $this->commands($this->commands);
    }
}
