<?php

namespace Robust\RealEstate\Providers;

use Illuminate\Support\ServiceProvider;

/**
 * Class RealEstateServiceProvider
 * @package Robust\RealEstate\Providers
 */
class RealEstateServiceProvider extends ServiceProvider
{
    protected $commands = [
        'Robust\RealEstate\Console\Commands\AdvanceSearch',
    ];
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->loadViewsFrom(__DIR__ . '/../../resources/views', 'real-estate');
        $this->register_includes();
    }

    public function register_includes()
    {
        $this->mergeConfigFrom(__DIR__ . '/../../config/permissions.php', 'real-estate.permissions');
        $this->mergeConfigFrom(__DIR__ . '/../../config/advance-search.php', 'mls.search');
        $this->commands($this->commands);
    }
}
