<?php
return [
    'data-pull' => [
        'property_class' => [
            'A' => 'Residential Property',
            'B' => 'MultiFamily',
            'C' => 'LotsAndLand',
            'D' => 'CommonInterest',
            'E' => 'Industry',
            'F' => 'Rental',
        ],
        'listing_fillable' => [
            'name',
            'slug',
            'uid',
            'mls_number',
            'class',
            'area',
            'sub_area',
            'borough_id',
            'system_price',
            'asking_price',
            'address_number',
            'address_street',
            'days_on_mls',
            'city',
            'zip',
            'state',
            'subdivision',
            'county',
            'elementary_school',
            'high_school',
            'middle_school',
            'picture_count',
            'picture_status',
            'input_date',
            'baths_full',
            'bedrooms',
            'status',
        ],
        'integer_fields' => [
            'total_finished_area',
            'system_price',
            'picture_count',
            'year_built',
            'bedrooms',
            'baths_full',
            'days_on_mls',
            'asking_price'
        ],
        'maps' => [
            'area' => 'area_id',
            'city' => 'city_id',
            'county' => 'county_id',
            'zip' => 'zip_id',
            'elementary_school' =>'elementary_school_id',
            'high_school' => 'high_school_id',
            'middle_school' => 'middle_school_id',
            'subdivision' => 'subdivision_id',
            'school_district' => 'school_district-id'
        ],
        'mapping' => [
            'city' => 'Robust\RealEstate\Models\City',
            'county' => 'Robust\RealEstate\Models\County',
            'area' => 'Robust\RealEstate\Models\Area',
            'elementary_school' => 'Robust\RealEstate\Models\ElementarySchool',
            'middle_school' => 'Robust\RealEstate\Models\MiddleSchool',
            'high_school' => 'Robust\RealEstate\Models\HighSchool',
            'zip' =>  'Robust\RealEstate\Models\Zip',
            'subdivision' =>  'Robust\RealEstate\Models\Subdivision',
            'school_district' =>  'Robust\RealEstate\Models\SchoolDistrict',
        ],
        'conditions' => [
            'cities' => [
                'A' => [
                    'Boca Raton' => '12LM4LA7AGIT',
                    'Delray Beach' => '12LM4LFDRK7J',
                    'Boynton Beach' => '12LM4LAAAHAJ',
                    'Deerfield Beach' => '12LM4LDYXFCY',
                    'West Palm Beach' => '12LM4O5ENL56',
                    'Palm Beach Gardens' => '12LM4LXYRE6N',
                    'Wellington' => '12LM4O5947SQ',
                    'Parkland' => '12LM4LZFOYMT',
                    'Highland Beach' => '12LM4LJ2YFPK'
                ],
                'B' => [
                    'Boca Raton' => '12MKUJQFXPDX',
                    'Delray Beach' => '12MKUJQFZ60O',
                    'Boynton Beach' => '12MKUJQFXSJY',
                    'Deerfield Beach' => '12MKUJQFZ36Z',
                    'West Palm Beach' => '12MKUJQG9O1Z',
                    'Palm Beach Gardens' => '12MKUJQG5OML',
                    'Wellington' => '12MKUJQG9I62',
                    'Parkland' => '12MKUJQG62XV',
                    'Highland Beach' => '12MKUJQG0PPA'
                ],
                'C' => [
                    'Boca Raton' => '12MKULNRNKCO',
                    'Delray Beach' => '12MKULNROXCD',
                    'Boynton Beach' => '12MKULNRNNQZ',
                    'Deerfield Beach' => '12MKULNROURY',
                    'West Palm Beach' => '12MKULNRZG1R',
                    'Palm Beach Gardens' => '12MKULNRVAO0',
                    'Wellington' => '12MKULNRZAFL',
                    'Parkland' => '12MKULNRVP1T',
                    'Highland Beach' => '12MKULNRQJPU'
                ],
                'D' => [
                    'Boca Raton' => '12MKV68SFIA8',
                    'Delray Beach' => '12MKV68SGVI5',
                    'Boynton Beach' => '12MKV68SFLN7',
                    'Deerfield Beach' => '12MKV68SGSYQ',
                    'West Palm Beach' => '12MKV68SQV4T',
                    'Palm Beach Gardens' => '12MKV68SMV1D',
                    'Wellington' => '12MKV68SQQ3H',
                    'Parkland' => '12MKV68SN8LA',
                    'Highland Beach' => '12MKV68SIHSQ'
                ],
                'E' => [
                    'Boca Raton' => '12ML73ZYI3MK',
                    'Delray Beach' => '12ML73ZYJA99',
                    'Boynton Beach' => '12ML73ZYI5UB',
                    'Deerfield Beach' => '12ML73ZYJ7ZI',
                    'West Palm Beach' => '12ML73ZYRZFM',
                    'Palm Beach Gardens' => '12ML73ZYOSWB',
                    'Wellington' => '12ML73ZYRUKU',
                    'Parkland' => '12ML73ZYP4J0',
                    'Highland Beach' => '12ML73ZYKP3T'
                ],
                'F' => [
                    'Boca Raton' => '12MKV6FG7USK',
                    'Delray Beach' => '12MKV6FG98OD',
                    'Boynton Beach' => '12MKV6FG7XNQ',
                    'Deerfield Beach' => '12MKV6FG95TK',
                    'West Palm Beach' => '12MKV6FGJE87',
                    'Palm Beach Gardens' => '12MKV6FGF93M',
                    'Wellington' => '12MKV6FGJ8XZ',
                    'Parkland' => '12MKV6FGFOAU',
                    'Highland Beach' => '12MKV6FGASYE'
                ]
            ]
        ],
        'conditions_map' => [
            'counties' => 'LIST_41', 'system_price' =>'LIST_22','cities' => 'LIST_39'
        ],
        'min_price' => 10000,
        'limit' => 2000,
        'input' => 'LIST_132'
    ],
    'data-map'=>[
        'property' => [
            'listing' => [
                'A'=> [
                    'name' => 'LIST_1',
                    'slug' => 'LIST_1',
                    'uid' => 'LIST_1',
                    'mls_number' => 'LIST_105',
                    'class' => 'LIST_8',
                    'area' => 'LIST_29',
                    'system_price' => 'LIST_22',
                    'asking_price' => 'LIST_22',
                    'address_number' => 'LIST_31',
                    'address_street' => 'LIST_31',
                    'city' => 'LIST_39',
                    'state' => 'LIST_40',
                    'zip' => 'LIST_43',
                    'days_on_mls' => 'LIST_137',
                    'subdivision' => 'LIST_77',
                    'county' => 'LIST_41',
                    'elementary_school' => 'LIST_85',
                    'middle_school' => 'LIST_32',
                    'high_school' => 'LIST_73',
                    'picture_count' => 'LIST_133',
                    'input_date' => 'LIST_132',
                    'baths_full' => 'LIST_68',
                    'bedrooms' => 'LIST_66',
                    'status' => 'LIST_15',
                ],
                'B'=> [
                    'name' => 'LIST_1',
                    'slug' => 'LIST_1',
                    'uid' => 'LIST_1',
                    'mls_number' => 'LIST_105',
                    'class' => 'LIST_8',
                    'area' => 'LIST_29',
                    'system_price' => 'LIST_22',
                    'asking_price' => 'LIST_22',
                    'address_number' => 'LIST_31',
                    'address_street' => 'LIST_31',
                    'city' => 'LIST_39',
                    'state' => 'LIST_40',
                    'zip' => 'LIST_43',
                    'days_on_mls' => 'LIST_137',
                    'subdivision' => 'LIST_77',
                    'county' => 'LIST_41',
                    'elementary_school' => 'LIST_85',
                    'middle_school' => 'LIST_32',
                    'high_school' => 'LIST_73',
                    'picture_count' => 'LIST_133',
                    'input_date' => 'LIST_132',
                    'status' => 'LIST_15',
                ],
                'C'=> [
                    'name' => 'LIST_1',
                    'slug' => 'LIST_1',
                    'uid' => 'LIST_1',
                    'mls_number' => 'LIST_105',
                    'class' => 'LIST_8',
                    'area' => 'LIST_29',
                    'system_price' => 'LIST_22',
                    'asking_price' => 'LIST_22',
                    'address_number' => 'LIST_31',
                    'address_street' => 'LIST_31',
                    'city' => 'LIST_39',
                    'state' => 'LIST_40',
                    'zip' => 'LIST_43',
                    'days_on_mls' => 'LIST_137',
                    'subdivision' => 'LIST_77',
                    'county' => 'LIST_41',
                    'elementary_school' => 'LIST_85',
                    'middle_school' => 'LIST_32',
                    'high_school' => 'LIST_73',
                    'picture_count' => 'LIST_133',
                    'input_date' => 'LIST_132',
                    'status' => 'LIST_15',
                ],
                'D'=> [
                    'name' => 'LIST_1',
                    'slug' => 'LIST_1',
                    'uid' => 'LIST_1',
                    'mls_number' => 'LIST_105',
                    'class' => 'LIST_8',
                    'area' => 'LIST_29',
                    'system_price' => 'LIST_22',
                    'asking_price' => 'LIST_22',
                    'address_number' => 'LIST_31',
                    'address_street' => 'LIST_31',
                    'city' => 'LIST_39',
                    'state' => 'LIST_40',
                    'zip' => 'LIST_43',
                    'days_on_mls' => 'LIST_137',
                    'county' => 'LIST_41',
                    'elementary_school' => 'LIST_85',
                    'middle_school' => 'LIST_32',
                    'high_school' => 'LIST_73',
                    'picture_count' => 'LIST_133',
                    'input_date' => 'LIST_132',
                    'status' => 'LIST_15',
                ],
                'E'=> [
                    'name' => 'LIST_1',
                    'slug' => 'LIST_1',
                    'uid' => 'LIST_1',
                    'mls_number' => 'LIST_105',
                    'class' => 'LIST_8',
                    'area' => 'LIST_29',
                    'system_price' => 'LIST_22',
                    'asking_price' => 'LIST_22',
                    'address_number' => 'LIST_31',
                    'address_street' => 'LIST_31',
                    'city' => 'LIST_39',
                    'state' => 'LIST_40',
                    'zip' => 'LIST_43',
                    'days_on_mls' => 'LIST_137',
                    'subdivision' => 'LIST_77',
                    'county' => 'LIST_41',
                    'picture_count' => 'LIST_133',
                    'input_date' => 'LIST_132',
                    'status' => 'LIST_15',
                ],
                'F'=> [
                    'name' => 'LIST_1',
                    'slug' => 'LIST_1',
                    'uid' => 'LIST_1',
                    'mls_number' => 'LIST_105',
                    'class' => 'LIST_8',
                    'area' => 'LIST_29',
                    'system_price' => 'LIST_22',
                    'asking_price' => 'LIST_22',
                    'address_number' => 'LIST_31',
                    'address_street' => 'LIST_31',
                    'city' => 'LIST_39',
                    'state' => 'LIST_40',
                    'zip' => 'LIST_43',
                    'days_on_mls' => 'LIST_137',
                    'subdivision' => 'LIST_77',
                    'county' => 'LIST_41',
                    'elementary_school' => 'LIST_85',
                    'middle_school' => 'LIST_32',
                    'high_school' => 'LIST_73',
                    'picture_count' => 'LIST_133',
                    'input_date' => 'LIST_132',
                    'status' => 'LIST_15',
                ],
            ],
            'properties' => [
                'A' => [
                    //property descriptions

                    //interior
                    'interior' => 'GF20121126194243819854000000',
                    'rooms' => 'GF20121128194256026088000000',
                    'furnished' => 'GF20121126194243781619000000',
                    'flooring' => 'GF20121126194243841543000000',
                    'amenities' => 'GF20121128203214100844000000',
                    'kitchen_equipment' => 'ROOM_KI_room_rem',
                    'baths_total'=> 'LIST_67',
                    'baths_half' => 'LIST_69',
                    'master_bath_bedroom' => 'GF20121128194227449710000000',
                    'design' => 'GF20121126194243751321000000',
                    'dining_area' => 'GF20121128203448419411000000',
                    'equestrian_features' => 'GF20140321152154756346000000',
                    'equipments' => 'GF20121128203422637850000000',
                    'utilities' => 'GF20121126194244411580000000',

                    //exterior
                    'exterior' => 'GF20121126194243919925000000',
                    'lot_description' => 'GF20121128194156807054000000',
                    'parking' => 'GF20121128203155695117000000',
                    'open_parking_space' => 'LIST_158',
                    'pool' => 'LIST_109',
                    'construction_status' => 'LIST_93',
                    'construction' => 'GF20121126194243835004000000',
                    'garage_spaces' => 'LIST_124',
                    'security' => 'GF20121126194243879313000000',
                    'special_info' => 'GF20121129160105603599000000',
                    'roof_type' => 'GF20121126194243845568000000',
                    'stories' => 'LIST_51',
                    'carport_spaces' => 'LIST_119',
                    'window_treatment' => 'GF20121128203631453311000000',
                    'guest_house' => 'GF20121128203514053297000000',

                    //Heating & cooling
                    'cooling_type' => 'GF20121128203359274284000000',
                    'heating_type' => 'GF20121126194243786373000000',

                    //view information
                    'view' => 'GF20121128190237228652000000',
                    'waterfront' => 'LIST_108',
                    'waterfront_details' => 'GF20121126194243720208000000',

                    //street information
                    'street_direction' => 'LIST_33',
                    'street_name' => 'LIST_34',
                    'street_post_dir' => 'LIST_36',
                    'street_suffix' => 'LIST_37',


                    // Address Information
                    'directions' => 'LIST_82',
                    'postal_code' => 'LIST_43',
                    'address' => 'LIST_31',
                    'unit_number' => 'LIST_35',
                    'governing_bodies' => 'LIST_59',
                    'zoning' => 'LIST_74',
                    'builder_name' => 'LIST_113',
                    'geo_area' => 'LIST_86',
                    'development_name' => 'LIST_130',
                    'dock' => 'LIST_122',

                    //size & dimensions
                    'living_square_feet' => 'LIST_48',
                    'total_square_feet' => 'LIST_49',
                    'guest_house_square_feet' => 'LIST_50',
                    'square_feet_source' => 'LIST_97',
                    'lot_size' => 'LIST_118',
                    'unit_floor' => 'LIST_123',
                    'covered_space' => 'LIST_24',
                    'lot_dimensions' => 'LIST_56',

                    //extra information
                    'mls_approved' => 'LIST_4',
                    'pets_allowed' => 'LIST_112',
                    'pet_restriction' => 'GF20180201155859549336000000',
                    'virtual_tour' => 'UNBRANDEDIDXVIRTUALTOUR',
                    'mobile_features' => 'GF20121128190158529252000000',
                    'possession' => 'GF20121128203750698912000000',

                    //terms & fees
                    'terms' => 'GF20121126194243889344000000',
                    'home_owner_association' => 'LIST_91',
                    'membership' => 'GF20121128203337846630000000',
                    'membership_fee' => 'LIST_148',
                    'front_exp' => 'LIST_58',
                    'selling_info' => 'LIST_131',
                    'multiple_offer' => 'LIST_115',
                    'dual_rate' => 'LIST_116',
                    'application_fee' => 'LIST_121',
                    'list_price_per_square_feet' => 'LIST_125',
                    'sold_price_per_square_feet' => 'LIST_126',
                    'hopa' => 'LIST_96',
                    'total_tax' => 'LIST_75',
                    'tax_year' => 'LIST_76',
                    'legal_description' => 'LIST_81',
                    'maintenance_fee_inclusive' => 'GF20121128203245813130000000',
                    'document_count' => 'LIST_162',
                    'terms_of_sale' => 'LIST_28',


                    //others
                    'uid' => 'LIST_1',
                    'property_group' => 'LIST_7',
                    'list_agent' => 'LIST_5',
                    'modification_date' => 'LIST_87',
                    'property_type' => 'LIST_9',
                    'expiration_date' => 'LIST_11',
                    'closing_date' => 'LIST_12',
                    'contract_date' => 'LIST_13',
                    'fallthrough_date' => 'LIST_14',
                    'status_change_date' => 'LIST_16',
                    'temp_off_market_date' => 'LIST_17',
                    'cancel_date' => 'LIST_18',
                    'contingent' => 'LIST_19',
                    'original_price' => 'LIST_21',
                    'sold_price' => 'LIST_23',
                    'latitude' => 'LIST_46',
                    'longitude' => 'LIST_47',
                    'year_built' => 'LIST_53',
                    'short_sale_addendum' => 'LIST_54',
                    'short_sale' => 'LIST_71',
                    'hardship_package' => 'LIST_72',
                    'public_remarks' => 'LIST_78',
                    'owners_name' => 'LIST_83',
                    'owners_phone' => 'LIST_84',
                    'list_type' => 'LIST_88',
                    'comm_brk' => 'LIST_89',
                    'list_off_agency' => 'LIST_90',
                    'model_name' => 'LIST_101',
                    'special_assessment' => 'LIST_110',
                    'short_sale_au' => 'LIST_113',
                    'owner' => 'LIST_150',
                    'auction' => 'LIST_154',
                    'broker_advertise' => 'LIST_157',
                    'update_date' => 'LIST_87',
                    'modified' => 'LIST_87',
                    'list_office' => 'listing_office_name',
                    'selling_office' => 'selling_office_name',


                    //Room dimensions
                    'balcony_length' => 'ROOM_BL_room_length',
                    'balcony_width' => 'ROOM_BL_room_width',
                    'family_room_length' => 'ROOM_FR_room_length',
                    'kitchen_length' => 'ROOM_KI_room_length',
                    'kitchen_width' => 'ROOM_KI_room_width',
                    'living_room_length' => 'ROOM_LV_room_length',
                    'living_room_width' => 'ROOM_LV_room_width',
                ],
                'B' => [
                    //property descriptions

                    //interior
                    'rooms' => 'FEAT20121227165041425649000000',
                    'furnished' => 'FEAT20121227165851095759000000',
                    'flooring' => 'GF20121206202430370061000000',
                    'amenities' => 'GF20121206202431812853000000',
                    'baths_total'=> 'FEAT20121227165211548718000000',
                    'baths_half' => 'FEAT20121227165537602365000000',
                    'utilities' => 'GF20121206202432180006000000',

                    //exterior
                    'exterior' => 'GF20121206202429990607000000',
                    'lot_description' => 'GF20121206202430654127000000',
                    'parking' => 'GF20121211024929412648000000',
                    'pool' => 'LIST_109',
                    'construction_status' => 'LIST_93',
                    'construction' => 'GF20121206202429699010000000',
                    'garage_spaces' => 'LIST_124',
                    'special_info' => 'GF20121206202431973610000000',
                    'roof_type' => 'GF20121206202431346706000000',
                    'stories' => 'LIST_64',
                    'carport_spaces' => 'LIST_119',
                    'window_treatment' => 'GF20121206202432413205000000',

                    //Heating & cooling
                    'cooling_type' => 'GF20121206202429621266000000',
                    'heating_type' => 'GF20121206202430480207000000',

                    //view information
                    'view' => 'GF20121206202432253492000000',
                    'waterfront' => 'LIST_108',
                    'waterfront_details' => 'GF20121206202432319685000000',

                    //street information
                    'street_direction' => 'LIST_33',
                    'street_name' => 'LIST_34',
                    'street_post_dir' => 'LIST_36',
                    'street_suffix' => 'LIST_37',


                    // Address Information
                    'directions' => 'LIST_82',
                    'postal_code' => 'LIST_43',
                    'address' => 'LIST_31',
                    'unit_number' => 'LIST_35',
                    'zoning' => 'LIST_74',
                    'geo_area' => 'LIST_86',
                    'development_name' => 'LIST_130',

                    //size & dimensions
                    'living_square_feet' => 'LIST_48',
                    'total_square_feet' => 'LIST_49',
                    'square_feet_source' => 'LIST_97',
                    'lot_size' => 'LIST_118',
                    'lot_dimensions' => 'LIST_56',

                    //extra information
                    'mls_approved' => 'LIST_4',
                    'virtual_tour' => 'UNBRANDEDIDXVIRTUALTOUR',
                    'possession' => 'GF20121206202431248446000000',

                    //terms & fees
                    'terms' => 'GF20121206202432075264000000',
                    'home_owner_association' => 'LIST_91',
                    'membership' => 'GF20121206202431107780000000',
                    'selling_info' => 'LIST_131',
                    'multiple_offer' => 'LIST_115',
                    'dual_rate' => 'LIST_116',
                    'application_fee' => 'LIST_121',
                    'list_price_per_square_feet' => 'LIST_125',
                    'sold_price_per_square_feet' => 'LIST_126',
                    'hopa' => 'LIST_96',
                    'total_tax' => 'LIST_75',
                    'tax_year' => 'LIST_76',
                    'legal_description' => 'LIST_81',
                    'maintenance_fee_inclusive' => 'GF20121206202430943072000000',
                    'document_count' => 'LIST_162',
                    'terms_of_sale' => 'LIST_28',


                    //others
                    'uid' => 'LIST_1',
                    'property_group' => 'LIST_7',
                    'list_agent' => 'LIST_5',
                    'modification_date' => 'LIST_87',
                    'property_type' => 'LIST_9',
                    'expiration_date' => 'LIST_11',
                    'closing_date' => 'LIST_12',
                    'contract_date' => 'LIST_13',
                    'fallthrough_date' => 'LIST_14',
                    'status_change_date' => 'LIST_16',
                    'temp_off_market_date' => 'LIST_17',
                    'cancel_date' => 'LIST_18',
                    'contingent' => 'LIST_19',
                    'original_price' => 'LIST_21',
                    'sold_price' => 'LIST_23',
                    'latitude' => 'LIST_46',
                    'longitude' => 'LIST_47',
                    'year_built' => 'LIST_53',
                    'short_sale_addendum' => 'LIST_54',
                    'short_sale' => 'LIST_71',
                    'hardship_package' => 'LIST_72',
                    'public_remarks' => 'LIST_78',
                    'owners_name' => 'LIST_83',
                    'owners_phone' => 'LIST_84',
                    'list_type' => 'LIST_88',
                    'comm_brk' => 'LIST_89',
                    'list_off_agency' => 'LIST_90',
                    'special_assessment' => 'LIST_110',
                    'short_sale_au' => 'LIST_113',
                    'owner' => 'LIST_150',
                    'auction' => 'LIST_154',
                    'broker_advertise' => 'LIST_157',
                    'update_date' => 'LIST_87',
                    'modified' => 'LIST_87',
                    'list_office' => 'listing_office_name',
                    'selling_office' => 'selling_office_name',
                ],
                'C' => [
                    //property descriptions

                    //exterior
                    'lot_depth' => 'LIST_51',
                    'lot_description' => 'GF20121206202840172334000000',
                    'special_info' => 'LIST_110',
                    'avail_docs' => 'GF20121212012128917589000000',
                    'buildings_include' => 'GF20121212011913198640000000',
                    'boat_service' => 'GF20121206202839083270000000',

                    //view information
                    'view' => 'GF20121206202841857761000000',
                    'waterfront' => 'LIST_108',
                    'waterfront_details' => 'GF20121206202841938447000000',

                    //street information
                    'street_direction' => 'LIST_33',
                    'street_name' => 'LIST_34',
                    'street_post_dir' => 'LIST_36',
                    'street_suffix' => 'LIST_37',


                    // Address Information
                    'directions' => 'LIST_82',
                    'postal_code' => 'LIST_43',
                    'address' => 'LIST_31',
                    'unit_number' => 'LIST_35',
                    'zoning' => 'LIST_74',
                    'builder_name' => 'LIST_113',
                    'geo_area' => 'LIST_86',
                    'development_name' => 'LIST_130',

                    //size & dimensions
                    'min_level_square_restricted' => 'LIST_49',
                    'leasable_square_feet' => 'LIST_50',
                    'lot_size' => 'LIST_118',
                    'unit_floor' => 'LIST_123',
                    'lot_dimensions' => 'LIST_56',

                    //extra information
                    'mls_approved' => 'LIST_4',
                    'virtual_tour' => 'UNBRANDEDIDXVIRTUALTOUR',

                    //terms & fees
                    'price_acre' => 'LIST_122',
                    'price_square' => 'LIST_123',
                    'terms' => 'GF20121206202841653258000000',
                    'home_owner_association' => 'LIST_91',
                    'membership' => 'GF20121206202840610602000000',
                    'front_exp' => 'LIST_58',
                    'selling_info' => 'LIST_131',
                    'multiple_offer' => 'LIST_115',
                    'dual_rate' => 'LIST_116',
                    'application_fee' => 'LIST_121',
                    'list_price_per_square_feet' => 'LIST_125',
                    'sold_price_per_square_feet' => 'LIST_126',
                    'total_tax' => 'LIST_75',
                    'tax_year' => 'LIST_76',
                    'legal_description' => 'LIST_81',
                    'document_count' => 'LIST_162',
                    'terms_of_sale' => 'LIST_28',


                    //others
                    'uid' => 'LIST_1',
                    'property_group' => 'LIST_7',
                    'list_agent' => 'LIST_5',
                    'modification_date' => 'LIST_87',
                    'property_type' => 'LIST_9',
                    'expiration_date' => 'LIST_11',
                    'closing_date' => 'LIST_12',
                    'contract_date' => 'LIST_13',
                    'fallthrough_date' => 'LIST_14',
                    'status_change_date' => 'LIST_16',
                    'temp_off_market_date' => 'LIST_17',
                    'cancel_date' => 'LIST_18',
                    'contingent' => 'LIST_19',
                    'original_price' => 'LIST_21',
                    'sold_price' => 'LIST_23',
                    'latitude' => 'LIST_46',
                    'longitude' => 'LIST_47',
                    'short_sale_addendum' => 'LIST_54',
                    'short_sale' => 'LIST_71',
                    'hardship_package' => 'LIST_72',
                    'public_remarks' => 'LIST_78',
                    'owners_name' => 'LIST_83',
                    'owners_phone' => 'LIST_84',
                    'list_type' => 'LIST_88',
                    'comm_brk' => 'LIST_89',
                    'list_off_agency' => 'LIST_90',
                    'model_name' => 'LIST_101',
                    'special_assessment' => 'LIST_110',
                    'short_sale_au' => 'LIST_113',
                    'owner' => 'LIST_150',
                    'auction' => 'LIST_154',
                    'broker_advertise' => 'LIST_157',
                    'update_date' => 'LIST_87',
                    'modified' => 'LIST_87',
                    'list_office' => 'listing_office_name',
                    'selling_office' => 'selling_office_name',
                ],
                'D' => [
                    //property descriptions

                    //building Info
                    'number_of_offices' => 'FEAT20121227211413283292000000',
                    'number_of_employees' => 'FEAT20121227211732273682000000',
                    'seating_capacity' => 'FEAT20121227211504168891000000',
                    'bar_stools' => 'FEAT20121227211748376588000000',
                    'door_height' => 'FEAT20121227211342123569000000',
                    'loading_docks' => 'FEAT20121227211525945049000000',

                    //exterior
                    'parking' => 'GF20121206202914938674000000',
                    'construction' => 'GF20121206202913690592000000',
                    'security' => 'GF20121206202915449375000000',
                    'special_info' => 'GF20121206202915832531000000',
                    'roof_type' => 'GF20121206202915832531000000',
                    'stories' => 'LIST_64',

                    //Heating & cooling
                    'cooling_type' => 'GF20121206202913609761000000',
                    'heating_type' => 'GF20121206202914323008000000',

                    //view information
                    'waterfront' => 'LIST_108',

                    //street information
                    'street_direction' => 'LIST_33',
                    'street_name' => 'LIST_34',
                    'street_post_dir' => 'LIST_36',
                    'street_suffix' => 'LIST_37',


                    // Address Information
                    'directions' => 'LIST_82',
                    'postal_code' => 'LIST_43',
                    'address' => 'LIST_31',
                    'unit_number' => 'LIST_35',
                    'zoning' => 'LIST_74',
                    'builder_name' => 'LIST_113',
                    'geo_area' => 'LIST_86',
                    'dock' => 'LIST_122',

                    //size & dimensions
                    'living_square_feet' => 'LIST_48',
                    'guest_house_square_feet' => 'LIST_50',
                    'square_feet_source' => 'LIST_97',


                    //extra information
                    'mls_approved' => 'LIST_4',
                    'virtual_tour' => 'UNBRANDEDIDXVIRTUALTOUR',
                    'possession' => 'GF20121206202915041661000000',

                    //terms & fees
                    'terms' => 'GF20121206202915944331000000',
                    'business_type' => 'LIST_91',
                    'selling_info' => 'LIST_131',
                    'multiple_offer' => 'LIST_115',
                    'dual_rate' => 'LIST_116',
                    'application_fee' => 'LIST_121',
                    'list_price_per_square_feet' => 'LIST_125',
                    'sold_price_per_square_feet' => 'LIST_126',
                    'total_tax' => 'LIST_75',
                    'tax_year' => 'LIST_76',
                    'legal_description' => 'LIST_81',
                    'maintenance_fee_inclusive' => 'GF20121206202914743943000000',
                    'document_count' => 'LIST_162',
                    'terms_of_sale' => 'LIST_28',


                    //others
                    'uid' => 'LIST_1',
                    'property_group' => 'LIST_7',
                    'list_agent' => 'LIST_5',
                    'modification_date' => 'LIST_87',
                    'property_type' => 'LIST_9',
                    'expiration_date' => 'LIST_11',
                    'closing_date' => 'LIST_12',
                    'contract_date' => 'LIST_13',
                    'fallthrough_date' => 'LIST_14',
                    'status_change_date' => 'LIST_16',
                    'temp_off_market_date' => 'LIST_17',
                    'cancel_date' => 'LIST_18',
                    'contingent' => 'LIST_19',
                    'original_price' => 'LIST_21',
                    'sold_price' => 'LIST_23',
                    'latitude' => 'LIST_46',
                    'longitude' => 'LIST_47',
                    'year_built' => 'LIST_53',
                    'short_sale_addendum' => 'LIST_54',
                    'short_sale' => 'LIST_71',
                    'hardship_package' => 'LIST_72',
                    'public_remarks' => 'LIST_78',
                    'owners_name' => 'LIST_83',
                    'owners_phone' => 'LIST_84',
                    'list_type' => 'LIST_88',
                    'comm_brk' => 'LIST_89',
                    'list_off_agency' => 'LIST_90',
                    'special_assessment' => 'LIST_110',
                    'short_sale_au' => 'LIST_113',
                    'owner' => 'LIST_150',
                    'auction' => 'LIST_154',
                    'broker_advertise' => 'LIST_157',
                    'update_date' => 'LIST_87',
                    'modified' => 'LIST_87',
                    'list_office' => 'listing_office_name',
                    'selling_office' => 'selling_office_name',
                ],
                'E' => [
                    //property descriptions

                    //building Info
                    'number_of_offices' => 'FEAT20121228141330591036000000',
                    'number_of_employees' => 'FEAT20121228141522363023000000',
                    'seating_capacity' => 'FEAT20121228141538045232000000',

                    //exterior
                    'construction' => 'GF20121206202935157741000000',
                    'security' => 'GF20121206202936970585000000',
                    'special_info' => 'GF20121206202937320302000000',
                    'roof_type' => 'GF20121206202936671897000000',
                    'stories' => 'LIST_64',

                    //Heating & cooling
                    'cooling_type' => 'GF20121206202935069920000000',
                    'heating_type' => 'GF20121206202935801841000000',

                    //view information
                    'waterfront' => 'LIST_108',
                    'waterfront_details' => 'GF20121206202937679400000000',

                    //street information
                    'street_direction' => 'LIST_33',
                    'street_name' => 'LIST_34',
                    'street_post_dir' => 'LIST_36',
                    'street_suffix' => 'LIST_37',


                    // Address Information
                    'directions' => 'LIST_82',
                    'postal_code' => 'LIST_43',
                    'address' => 'LIST_31',
                    'unit_number' => 'LIST_35',
                    'zoning' => 'LIST_74',
                    'geo_area' => 'LIST_86',

                    //size & dimensions
                    'total_square_feet' => 'LIST_48',
                    'square_feet_source' => 'LIST_97',
                    'lot_size' => 'LIST_57',

                    //extra information
                    'mls_approved' => 'LIST_4',
                    'virtual_tour' => 'UNBRANDEDIDXVIRTUALTOUR',
                    'possession' => 'GF20121206202936574401000000',

                    //terms & fees
                    'terms' => 'GF20121206202937431318000000',
                    'selling_info' => 'LIST_131',
                    'multiple_offer' => 'LIST_115',
                    'dual_rate' => 'LIST_116',
                    'application_fee' => 'LIST_121',
                    'list_price_per_square_feet' => 'LIST_125',
                    'sold_price_per_square_feet' => 'LIST_126',
                    'total_tax' => 'LIST_75',
                    'tax_year' => 'LIST_76',
                    'legal_description' => 'LIST_81',
                    'document_count' => 'LIST_162',
                    'terms_of_sale' => 'LIST_28',


                    //others
                    'uid' => 'LIST_1',
                    'property_group' => 'LIST_7',
                    'list_agent' => 'LIST_5',
                    'modification_date' => 'LIST_87',
                    'property_type' => 'LIST_9',
                    'expiration_date' => 'LIST_11',
                    'closing_date' => 'LIST_12',
                    'contract_date' => 'LIST_13',
                    'fallthrough_date' => 'LIST_14',
                    'status_change_date' => 'LIST_16',
                    'temp_off_market_date' => 'LIST_17',
                    'cancel_date' => 'LIST_18',
                    'contingent' => 'LIST_19',
                    'original_price' => 'LIST_21',
                    'sold_price' => 'LIST_23',
                    'latitude' => 'LIST_46',
                    'longitude' => 'LIST_47',
                    'year_built' => 'LIST_53',
                    'hardship_package' => 'LIST_72',
                    'public_remarks' => 'LIST_78',
                    'owners_name' => 'LIST_83',
                    'owners_phone' => 'LIST_84',
                    'list_type' => 'LIST_88',
                    'comm_brk' => 'LIST_89',
                    'list_off_agency' => 'LIST_90',
                    'owner' => 'LIST_150',
                    'auction' => 'LIST_154',
                    'broker_advertise' => 'LIST_157',
                    'update_date' => 'LIST_87',
                    'modified' => 'LIST_87',
                    'list_office' => 'listing_office_name',
                    'selling_office' => 'selling_office_name',
                ],
                'F' => [
                    //property descriptions

                    //interior
                    'interior' => 'GF20121206203003177597000000',
                    'rooms' => 'GF20121206203004130697000000',
                    'furnished' => 'GF20121206203003026714000000',
                    'flooring' => 'GF20121206203002977441000000',
                    'amenities' => 'GF20121206203004466211000000',
                    'baths_total'=> 'LIST_67',
                    'baths_half' => 'LIST_69',
                    'master_bath_bedroom' => 'GF20130917171925858182000000',
                    'equestrian_features' => 'FEAT20140321161032643134000000',
                    'equipments' => 'GF20121206203002864650000000',

                    //exterior
                    'exterior' => 'GF20121206203002756811000000',
                    'lot_description' => 'GF20160822140722485295000000',
                    'parking' => 'GF20121206203003854226000000',
                    'pool' => 'LIST_109',
                    'garage_spaces' => 'LIST_124',
                    'security' => 'GF20121206203004310572000000',
                    'carport_spaces' => 'LIST_119',

                    //Heating & cooling
                    'cooling_type' => 'GF20121206203002461896000000',
                    'heating_type' => 'GF20121206203003104396000000',

                    //view information
                    'view' => 'GF20121206203004843709000000',
                    'waterfront' => 'LIST_108',
                    'waterfront_details' => 'GF20121206203004910529000000',

                    //street information
                    'street_direction' => 'LIST_33',
                    'street_name' => 'LIST_34',
                    'street_post_dir' => 'LIST_36',
                    'street_suffix' => 'LIST_37',


                    // Address Information
                    'directions' => 'LIST_82',
                    'postal_code' => 'LIST_43',
                    'address' => 'LIST_31',
                    'governing_bodies' => 'LIST_59',
                    'geo_area' => 'LIST_86',
                    'development_name' => 'LIST_130',
                    'dock' => 'LIST_122',

                    //size & dimensions
                    'living_square_feet' => 'LIST_48',
                    'total_square_feet' => 'LIST_49',
                    'lot_size' => 'LIST_118',
                    'unit_floor' => 'LIST_123',

                    //extra information
                    'mls_approved' => 'LIST_4',
                    'pets_allowed' => 'LIST_112',
                    'virtual_tour' => 'UNBRANDEDIDXVIRTUALTOUR',

                    //terms & fees
                    'membership' => 'GF20121206203003810971000000',
                    'front_exp' => 'LIST_58',
                    'selling_info' => 'LIST_131',
                    'dual_rate' => 'LIST_116',
                    'application_fee' => 'LIST_121',
                    'cleaning_fee' => 'LIST_120',
                    'rental_price_per_square_feet' => 'LIST_125',
                    'rented_price_per_square_feet' => 'LIST_126',
                    'hopa' => 'LIST_96',
                    'legal_description' => 'LIST_81',
                    'document_count' => 'LIST_162',
                    'terms_of_sale' => 'LIST_28',


                    //others
                    'uid' => 'LIST_1',
                    'property_group' => 'LIST_7',
                    'list_agent' => 'LIST_5',
                    'modification_date' => 'LIST_87',
                    'property_type' => 'LIST_9',
                    'expiration_date' => 'LIST_11',
                    'closing_date' => 'LIST_12',
                    'contract_date' => 'LIST_13',
                    'fallthrough_date' => 'LIST_14',
                    'status_change_date' => 'LIST_16',
                    'temp_off_market_date' => 'LIST_17',
                    'cancel_date' => 'LIST_18',
                    'contingent' => 'LIST_19',
                    'original_price' => 'LIST_21',
                    'sold_price' => 'LIST_23',
                    'latitude' => 'LIST_46',
                    'longitude' => 'LIST_47',
                    'year_built' => 'LIST_53',
                    'public_remarks' => 'LIST_78',
                    'owners_name' => 'LIST_83',
                    'owners_phone' => 'LIST_84',
                    'list_type' => 'LIST_88',
                    'comm_brk' => 'LIST_89',
                    'list_off_agency' => 'LIST_90',
                    'model_name' => 'LIST_101',
                    'owner' => 'LIST_150',
                    'auction' => 'LIST_154',
                    'broker_advertise' => 'LIST_157',
                    'update_date' => 'LIST_87',
                    'modified' => 'LIST_87',
                    'list_office' => 'listing_office_name',
                    'selling_office' => 'selling_office_name',

                    //Room dimensions
                    'balcony_length' => 'ROOM_BL_room_length',
                    'balcony_width' => 'ROOM_BL_room_width',
                    'family_room_length' => 'ROOM_FR_room_length',
                    'kitchen_length' => 'ROOM_KI_room_length',
                    'kitchen_width' => 'ROOM_KI_room_width',
                    'living_room_length' => 'ROOM_LV_room_length',
                    'living_room_width' => 'ROOM_LV_room_width',
                ],
            ]

        ]
    ],
    'listing_detail' => [

    ]
];
